#! /bin/bash

#if [ ! $# == 1 ]; then
    # echo "Usage: $0 [desktop | cluster | imac]"
    # exit
#fi

dir=testdir

if [ -e ${dir}/osm_polygon_europe.snapshot.txt ] && [ -e ${dir}/osm_polygon_planet.snapshot.txt ] 
then
    echo "All testing infrastructure is present."
else 
    echo "Test cases are missing... Can't do test without them."
    exit 1
fi


# create the test files.
make -f Makefile

# test 1 
echo -n "TEST: Map --- "

export map_input_file="planet.1"
./mapper < ${dir}/osm_polygon_planet.snapshot.txt  > ${dir}/map.planet.mr

export map_input_file="planet.2"
./mapper < ${dir}/osm_polygon_europe.snapshot.txt  > ${dir}/map.europe.mr

diff ${dir}/map.planet.db ${dir}/map.planet.mr >/dev/null 2>&1

if [ $? -ne 0 ]
then
    echo "failed."
else
    echo "passed."
    cat ${dir}/map.planet.mr ${dir}/map.europe.mr > ${dir}/reduce.in
    rm ${dir}/map.planet.mr
    rm ${dir}/map.europe.mr
fi

# test 2

echo -n "TEST: Reduce --- "


./reducer< ${dir}/reduce.in 2>/tmp/serr.txt | cut -f2 | sort -n > ${dir}/reduce.out.mr

diff ${dir}/reduce.out.db ${dir}/reduce.out.mr >/dev/null 2>&1

if [ $? -ne 0 ]
then
    echo "failed."
else
    echo "passed."
    cat /tmp/serr.txt
    rm /tmp/serr.txt
    rm ${dir}/reduce.in
    rm ${dir}/reduce.out.mr
fi

make clean

