CREATE TABLE IF NOT EXISTS ta ( tile_id STRING, rec_id STRING, outline STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' ;
CREATE TABLE IF NOT EXISTS tb ( tile_id STRING, rec_id STRING, outline STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' ;

