CREATE TABLE IF NOT EXISTS tc ( tile_id STRING, d_id STRING, rec_id STRING, a STRING, b STRING, c STRING, d STRING, e STRING, f STRING, g STRING, outline STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' ;

CREATE TABLE IF NOT EXISTS td ( tile_id STRING, d_id STRING, rec_id STRING, a STRING, b STRING, c STRING, d STRING, e STRING, f STRING, g STRING, outline STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' ;
